name: webhook
services:
    webhook:
        container_name: webhook
        ports:
            - 8548:80
        build: .
        dns:
            - "1.0.0.1"
            - "1.1.1.1"
        restart: unless-stopped
        image: webhook
        volumes:
            - ./app/history.json:/code/history.json